---
# tasks file for roles/firewall_defense
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Set Default Policy to Deny Incoming
  ufw: 
    direction: incoming
    policy: deny

- name: Allow SSH with Rate Limiting
  ufw:
    rule: limit
    port: "{{ item }}"
    proto: tcp
  loop: "{{ allowed_ports }}"
#limit blocks IP id 6 connections are made in 30 sec

- name: Enable UFW
  ufw:
    state: enabled
